// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: owner.sql

package db

import (
	"context"
	"time"
)

const createOwner = `-- name: CreateOwner :one
INSERT INTO owners (
  "first_name",
  "first_surname",
  "second_surname",
  "born_at",
  "nationality"
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, first_name, first_surname, second_surname, born_at, nationality
`

type CreateOwnerParams struct {
	FirstName     string    `json:"first_name"`
	FirstSurname  string    `json:"first_surname"`
	SecondSurname string    `json:"second_surname"`
	BornAt        time.Time `json:"born_at"`
	Nationality   int32     `json:"nationality"`
}

func (q *Queries) CreateOwner(ctx context.Context, arg CreateOwnerParams) (Owner, error) {
	row := q.db.QueryRowContext(ctx, createOwner,
		arg.FirstName,
		arg.FirstSurname,
		arg.SecondSurname,
		arg.BornAt,
		arg.Nationality,
	)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.FirstSurname,
		&i.SecondSurname,
		&i.BornAt,
		&i.Nationality,
	)
	return i, err
}
