apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::356062354528:user/ci-github
      username: ci-github
      groups:
        - system:masters
        
